language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
#  - hhvm
#  - nightly

addons:
  ssh_known_hosts: hoessl.eu

before_install:
  - openssl aes-256-cbc -K $encrypted_f3a6d9a4845e_key -iv $encrypted_f3a6d9a4845e_iv -in assets/travis/travis.key.enc -out assets/travis/travis.key -d
  - chmod 600 assets/travis/travis.key

install:
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer install --dev --prefer-dist
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e 'create database antragsgruen;'
  - mysql -e 'create database antragsgruen_tests;'
  - cp assets/travis/config.php config/
  - cp assets/travis/config_tests.php config/
  - wget https://www.hoessl.eu/phantomjs
  - chmod a+x phantomjs


before_script:
  - "export DISPLAY=:99.0"
  - "Xvfb :99.0 -extension RANDR > xvfb.log &"
  - "phantomjs --webdriver=4444 > phantomjs.log 2>&1 &"
  - nohup php -S localhost:8080 -t web/ > php.log 2>&1 &
  - sleep 5

script:
  - cd tests
  - ./run.sh
  - touch codeception/_output/test
  - scp -r -i ../assets/travis/travis.key codeception/_output/* travis@hoessl.eu:~/output/
  - scp -r -i ../assets/travis/travis.key ../xvfb.log ../phantomjs.log ../php.log travis@hoessl.eu:~/output/
