language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
#  - hhvm
#  - nightly

install:
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer install --dev --prefer-dist
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e 'create database antragsgruen;'
  - mysql -e 'create database antragsgruen_tests;'
  - cp assets/travis/config.php config/
  - cp assets/travis/config_tests.php config/
  - wget https://www.hoessl.eu/phantomjs
  - chmod a+x phantomjs


before_script:
  - "export DISPLAY=:99.0"
  - "Xvfb :99.0 -extension RANDR > /dev/null &"
  - "phantomjs --webdriver=4444 > /dev/null 2>/dev/null &"
  - sleep 5

script:
  - cd tests
  - ./run.sh
