language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
#  - hhvm
#  - nightly

addons:
  ssh_known_hosts: hoessl.eu

before_install:
  - openssl aes-256-cbc -K $encrypted_f3a6d9a4845e_key -iv $encrypted_f3a6d9a4845e_iv -in assets/travis/travis.key.enc -out assets/travis/travis.key -d
  - chmod 600 assets/travis/travis.key

install:
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer install --dev --prefer-dist
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e 'create database antragsgruen;'
  - mysql -e 'create database antragsgruen_tests;'
  - cp assets/travis/config.php config/
  - cp assets/travis/config_tests.php config/
  - wget https://www.hoessl.eu/phantomjs
  - chmod a+x phantomjs


before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f assets/travis/apache.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  #
  - "./phantomjs --webdriver=4444 > phantomjs.log 2>&1 &"
  - sleep 5

script:
  - cd tests
  - ./run.sh
  - cd ..
  - touch tests/codeception/_output/test
  - scp -r -i ../assets/travis/travis.key tests/codeception/_output/* travis@hoessl.eu:~/output/
  - scp -r -i ../assets/travis/travis.key /etc/apache2/sites-available/default travis@hoessl.eu:~/runtime/
  - scp -r -i ../assets/travis/travis.key phantomjs.log travis@hoessl.eu:~/logs/
  - scp -r -i ../assets/travis/travis.key runtime/* travis@hoessl.eu:~/runtime/
  - scp -r -i ../assets/travis/travis.key /var/log/apache2/* travis@hoessl.eu:~/logs/
